server:
  port: 8080
spring:
  application:
    name: local-grpc-client

grpc:
  client:
    my-springboot-grpc-server:
      host:
        - 127.0.0.1
      port:
        - 9898
      enableKeepAlive: true
      keepAliveWithoutCalls: true